In [1]:
import numpy as np
from nnfs.datasets import spiral_data
from moonet import MooNet as mn, Relu, SoftMax

In [2]:
# X is the input data, y is the labeled output data
X,y = spiral_data(samples=100, classes=3)

# defining layer 1, with 2 input features and 3 neurons
dense1 = mn(2,3)
# defining layer 2, with 3 input(output of layer 1) and 3 neurons
dense2 = mn(3,3)
# activation functions
activation1 = Relu()
activation2 = SoftMax()

# passing data through layer 1
dense1.forward_pass(X)
# applying relu activation on layer 1
activation1.forward_pass(dense1.output)
# passing the output of layer 1 to layer 2
dense2.forward_pass(activation1.output)
# this being the final layer, we apply softmax activation
activation2.forward_pass(activation1.output)


print(activation2.output)

[[0.33333333 0.33333333 0.33333333]
 [0.33331709 0.33331684 0.33336607]
 [0.33326914 0.33329324 0.33343762]
 [0.33323732 0.33327848 0.3334842 ]
 [0.33325331 0.3332648  0.33348189]
 [0.33321172 0.33324472 0.33354356]
 [0.33314362 0.33320719 0.33364918]
 [0.33318659 0.33318659 0.33362682]
 [0.33308432 0.33318721 0.33372847]
 [0.33304739 0.33314655 0.33380606]
 [0.33310279 0.33310279 0.33379442]
 [0.33308182 0.33308182 0.33383637]
 [0.33306309 0.33306309 0.33387382]
 [0.33298378 0.33300967 0.33400656]
 [0.33303582 0.33303582 0.33392835]
 [0.33323426 0.33323426 0.33353147]
 [0.33295431 0.33295431 0.33409138]
 [0.33316155 0.33316155 0.33367689]
 [0.33328382 0.33328382 0.33343236]
 [0.33306178 0.33306178 0.33387643]
 [0.33297664 0.33297664 0.33404673]
 [0.33316796 0.33316796 0.33366408]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33

In [15]:
y_pred[0,0]

np.float64(0.3333333333333333)

In [24]:
y_pred = activation2.output

# feature engineering for one hot encoding of labels
y_new = []
for i in y:
    if i == 0:
        y_new.append([1,0,0])
    elif i == 1:
        y_new.append([0,1,0])
    else:
        y_new.append([0,0,1])

L0 = -1*np.sum(y_new*np.log(y_pred))
# making the calculations faster
L1 = 0
for i in y:
    if i == 0:
        L1 += -1*np.sum(np.log(y_pred[i,0]))
    elif i == 1:
        L1 += -1*np.sum(np.log(y_pred[i,1]))
    else:
        L1 += -1*np.sum(np.log(y_pred[i,2]))

L2 = []
for i in range(len(y_pred)):
    if y[i] == 0:
        L2.append(y_pred[i,0])
    elif i == 1:
        L2.append(y_pred[i,1])
    else:
        L2.append(y_pred[i,2])


L3 = -1*np.sum(np.log(y_pred[[i for i in range(300)], y]))
print(L0,L1,-1*np.sum(np.log(L2)),np.mean(L3))

329.6851981790004 329.5573538576767 329.3400706076312 329.68519817900034
